### ISSUE TITLE
Release keras-vis 0.4.2 ( or 0.5?)

### ISSUE THREAD

**Issue by keisen** [raghakot/keras-vis#141]
I think, we should release new version of keras-vis.
The cause of lately issues was almost fixed in currently master branch.

Please let me know If there is any problem.

**Comment by keisen** [comment]
I can do most of the release work (i.e., edit `setup.py`, archive, update docs and etc. ) .
@raghakot , Could you please publish to PyPI, after I'll done it ?

BTW, because we do not do it, There is `keras-vis-temp` (ver 0.4.2) in PyPI. lol.

**Comment by keisen** [comment]
### Tasks

- [x] update `setup.py`
- [x] improve documents
- [ ] update document (in gh-pages branch)
- [ ] merge PR #150 
- [ ] create archive and tag
- [ ] publish to PYPI

**Comment by ManifoldFR** [comment]
Is a release still planned ? The bugfix for the "fed and fetched" issue #127 could be useful for some people installing their entire ML stack from PyPI without checking

**Comment by xiaohk** [comment]
+1 for releasing a new version to fix "fix and fetched" issue
